### ISSUE TITLE
Suggestion: Add optional date param to KSUID.random and KSUID.randomSync.

### ISSUE THREAD

**Issue by codeitcody** [novemberborn/ksuid#17]
This is an incredibly useful library, thank you!

I often already have a date before generating a KSUID. An example is when I insert multiple related items into the database that I want to all have the same timestamp.

I'd love the option to do pass in a date object or ms-epoch value:
```javascript
const createdAt = new Date()
// ...
const id = await KSUID.random(createdAt) // or KSUID.random(createdAt.getTime())
```

I can do this using KSUID.fromParts of course but that requires a little more work to generate the random payload. This would make it slightly easier.

**Comment by novemberborn** [comment]
Sounds good. PR welcome :smile:

**Comment by robbiecode** [comment]
Hi Guys,
I put something like that for myself as I need to have easy way to move code between NODE and PHP:

$ksuid = new Ksuid;
echo $ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3');
//or
$dec=json_decode($ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3'));
echo $dec->timestamp;


    public function Parse($dat): string
    {
        $encoded = (new Base62)->decode($dat);
        $hex=bin2hex($encoded);
        $hexpl=bin2hex(substr($encoded,5,20));
        $hexts=bin2hex(substr($encoded,0,4));
        $ts=hexdec($hexts);
        $ep=1400000000+$ts;
        return json_encode(['epoch'=>$ep,'timestamp'=>$ts,'hexid'=>$hex,'hexpl'=>$hexpl,'hexts'=>$hexts]);
    }

Maybe you can adapt it for other users.

**Comment by robbiecode** [comment]
The function was added to your /src/Ksuid.php  on my dev server:

$ksuid = new Ksuid;
echo $ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3');
$dec=json_decode($ksuid->Parse('1cMEmaJtIKIZxsPALGX6gD4C0r3'));
echo $dec->timestamp;


    public function Parse($dat): string
    {
        $encoded = (new Base62)->decode($dat);
        $hex=bin2hex($encoded);
        $hexpl=bin2hex(substr($encoded,5,20));
        $hexts=bin2hex(substr($encoded,0,4));
        $ts=hexdec($hexts);
        $ep=1400000000+$ts;
        return json_encode(['epoch'=>$ep,'timestamp'=>$ts,'hexid'=>$hex,'hexpl'=>$hexpl,'hexts'=>$hexts]);
    }
