### ISSUE TITLE
Re: PR #17

### ISSUE THREAD

**Issue by waimun** [novemberborn/ksuid#20]
Doesn't seem to work with earlier (or some...) dates ?

For example:
```js
KSUID.randomSync(new Date(2005,11,5))
```

Error:
```
RangeError [ERR_OUT_OF_RANGE]: The value of "value" is out of range. It must be >= 0 and <= 4294967295. Received -266241200
```

cc: @novemberborn @amdolan

**Comment by amdolan** [comment]
@waimun From the original repo: https://github.com/segmentio/ksuid

>The timestamp epoch is adjusted to March 5th, 2014, providing over 100 years of life.

In other words, it should not work for dates before March 5, 2014.  Perhaps it could be better documented.

**Comment by waimun** [comment]
@amdolan Thanks for pointing this out! I had no idea until I read their guide. Seems like it is some time in May 13, 2014 from my test. Perhaps it could be better documented somewhere like you said. 👍
