### ISSUE TITLE
Using KSUID in angular

### ISSUE THREAD

**Issue by planesandunicorns** [novemberborn/ksuid#21]
Hi there,
I'm using KSUID as id on my Golang API. Now I'm trying to use your package in my angular app, but I'm a bit stumped as to getting it to work.
Somebody got a few minutes to write a tiny example of how to use it in Angular?

I tried:

`import ksuid = require('ksuid');`
> ReferenceError: Can't find variable: ksuid

`import * as ksuid from 'ksuid';`
>  Cannot access uninitialized variable.

`import ksuid from 'ksuid';`
>  Cannot access uninitialized variable.

Any pointers would be highly appreciated!

**Comment by novemberborn** [comment]
To be honest I can't figure out these TS imports beyond "works for me based on my config". All of those look fine? 🤷 

Your bigger problem is that this library is written for Node.js and I wouldn't know how you'd use it in a browser. Happy to take a PR which adds browser compatibility if it's done in a clean way.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by planesandunicorns** [comment]
Thanks @novemberborn, need to get it to work first! Maybe the repo [https://github.com/xaviiic/xid-js](https://github.com/xaviiic/xid-js) could be of some use? I believe XID and KSUID have similarities?
I will stick to a time ordered UUID V1 for now. Maybe I'll have a look when I've got some more time on my hands. KSUID is still a very promising concept in my humble opinion.
