### ISSUE TITLE
strings are not sortable

### ISSUE THREAD

**Issue by EyadAlghamdi** [novemberborn/ksuid#26]
hi,
I am trying to use this library to generate IDs in MySQL and store it as a sortable string,
I generated 8 IDs, but it is not sortable by creation time? 

here is a screenshot of the generated ID's, the `name` column should have been ordered 1..8 when the ID column is sorted.
 
![Screen Shot 2022-02-25 at 1 30 41 PM](https://user-images.githubusercontent.com/58611925/155768759-68e04a14-1464-4fb5-aa8f-fb1248229285.png)

Am I missing something in how I'm implementing it?
I'm just using 

```ts
id: (await KSUID.random()).string,
```

**Comment by novemberborn** [comment]
I don't know, you'll have to compare this with the Go lang implementation and if there is a divergence I'll accept a PR to make this compatible.

**Comment by adamstickley** [comment]
Were all of these generated within the same second? Regular use-cases for KSUIDs have a 1-second resolution.

**Comment by EyadAlghamdi** [comment]
@adamstickley i tested this in production and every once in a while i get a new unordered ID that gets lost in the middle. Im not sure why that is. Im searching to see if there is a fix, since this is a major issue for me :( 

Also, i waited more than a second between entries just to be safe
