### ISSUE TITLE
How to use isValid?

### ISSUE THREAD

**Issue by darbio** [novemberborn/ksuid#27]
How do we use `isValid`? When I call it using a buffer generated from a string, it always returns false regardless of whether the ksuid is valid or not.

Example:

```
import ksuid from 'ksuid';

const id = ksuid.randomSync().string; // 2GZ2KKxYNaHLlhuwOWWGyOhKftp
const isValid = ksuid.isValid(Buffer.from(id, 'utf8')); // false
```

**Comment by novemberborn** [comment]
The string encoding isn't in UTF8, use `ksuid.parse()` to convert it to a buffer.
