### ISSUE TITLE
Does it store milliseconds?

### ISSUE THREAD

**Issue by waimun** [novemberborn/ksuid#28]
const v = k.randomSync(new Date('2022-12-17T03:40:29.204Z'))
const v2 = k.randomSync(new Date('2022-12-17T03:40:29.300Z'))

For example: `v.date.toISOString()` doesn't seem to retain the ms value of 204.

It seems like I can't rely on the sorting because `[v,v2].sort()` will list v2 as the first one. Is there a way to reliably sort the 27 chars string based on the milliseconds precision or am I missing something here? Thanks!

cc: @novemberborn @amdolan

**Comment by novemberborn** [comment]
I believe the timestamp component has second accuracy. Sorting is not precise. See https://github.com/segmentio/ksuid for more background.

**Comment by amdolan** [comment]
@waimun you may want to look into UUIDv7, rather than ksuid.  UUIDv7 was not well supported a few years ago, but has sub millisecond accuracy and is sortable, and I'm seeing that it's gaining some adoption.
